FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 3001 available to the world outside this container
EXPOSE 3001

# Define environment variable
# ENV NAME World

# Run main.py when the container launches
CMD ["python", "main.py"]